// play-scala-react/client/src/App.js
import logo from './logo.svg';
import './App.css';
import AngularRemoteApp from "./modules/AngularRemoteApp";
import Notifications from "./components/notifications/Notifications";
import Actions from "./components/actions/Actions";
import {useEffect} from "react";
import windowEventBridge from "./services/WindowEventBridge";

function App() {

    useEffect(() => {
        // start listening events from other apps
        windowEventBridge.start();

        return () => {
            // stop listening events from other apps
            windowEventBridge.stop();
        };
    },[]);

    return (
        <div className="App">
            <header className="App-header">
                <img src={logo} className="App-logo" alt="logo" />
                <h4>Host</h4>
                <Actions></Actions>
                <Notifications></Notifications>
            </header>
            <AngularRemoteApp></AngularRemoteApp>
        </div>
    );
}

export default App;

// play-scala-angular/client/src/app/app.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {WindowEventBridgeService} from "./services/window-event-bridge.service";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent implements OnInit, OnDestroy{
  title = 'client';

  constructor(private bridge: WindowEventBridgeService) {}

  ngOnInit() {
    // start listening events from other apps
    this.bridge.start();
  }

  ngOnDestroy() {
    // stop listening events from other apps
    this.bridge.stop();
  }

}

<!-- Toolbar -->
<div class="toolbar" role="banner">
  <img
    width="40"
    alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
  />
  <h4>Remote</h4>
  <app-actions></app-actions>
  <app-notifications></app-notifications>
</div>
