// play-scala-react/client/src/components/actions/Actions.js
import React from "react";
import './Actions.css';
import windowEventBridge from "../../services/WindowEventBridge";

const Actions = () => {
    const sendMessage = () => {
        // dispatch event to other apps
        windowEventBridge.dispatch('Window event dispatched from React')
    };
    return <button onClick={sendMessage}>Notify Remote</button>;
};

export default Actions;

// play-scala-angular/client/src/app/components/actions/actions.component.ts
import { Component } from '@angular/core';
import {WindowEventBridgeService} from "../../services/window-event-bridge.service";

@Component({
  selector: 'app-actions',
  templateUrl: './actions.component.html',
  styleUrls: ['./actions.component.sass']
})
export class ActionsComponent {
  constructor(private bridge: WindowEventBridgeService) {}

  public sendMessage(): void {
    // dispatch event to other apps
    this.bridge.dispatch('Window event dispatched from Angular');
  }
}

<button (click)="sendMessage()">Notify Host</button>
